import { useState } from 'react'
import { motion } from 'framer-motion'
import { QRCodeSVG } from 'qrcode.react'
import Modal from '@/components/molecules/Modal'
import Button from '@/components/atoms/Button'
import { Copy, Check } from 'lucide-react'

interface CryptoPaymentModalProps {
  isOpen: boolean
  onClose: () => void
  amount: number
}

type CryptoType = 'btc' | 'eth' | 'ltc' | 'usdc' | 'usdt' | 'bnb'

export default function CryptoPaymentModal({ isOpen, onClose, amount }: CryptoPaymentModalProps) {
  const [selectedCrypto, setSelectedCrypto] = useState<CryptoType | null>(null)
  const [copied, setCopied] = useState(false)

  const cryptoOptions = [
    { id: 'btc' as CryptoType, name: 'Bitcoin', symbol: 'BTC', color: '#F7931A' },
    { id: 'eth' as CryptoType, name: 'Ethereum', symbol: 'ETH', color: '#627EEA' },
    { id: 'ltc' as CryptoType, name: 'Litecoin', symbol: 'LTC', color: '#345D9D' },
    { id: 'usdc' as CryptoType, name: 'USD Coin', symbol: 'USDC', color: '#2775CA' },
    { id: 'usdt' as CryptoType, name: 'Tether', symbol: 'USDT', color: '#26A17B' },
    { id: 'bnb' as CryptoType, name: 'Binance Coin', symbol: 'BNB', color: '#F3BA2F' },
  ]

  // Mock wallet addresses (in production, these would be generated by backend)
  const walletAddresses: Record<CryptoType, string> = {
    btc: '1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa',
    eth: '0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb',
    ltc: 'LQTpS7fJPHR9bYW8t5qPz3G7rZB9cKvXm7',
    usdc: '0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb',
    usdt: '0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb',
    bnb: '0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb',
  }

  const handleCopyAddress = (address: string) => {
    navigator.clipboard.writeText(address)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <Modal isOpen={isOpen} onClose={onClose} title="Crypto Payment" size="lg">
      <div className="space-y-6">
        {!selectedCrypto ? (
          <>
            <div className="bg-gradient-to-r from-orange-500 to-yellow-500 text-white p-6 rounded-xl text-center">
              <p className="text-sm opacity-90 mb-1">Amount</p>
              <p className="text-4xl font-bold">${amount.toFixed(2)}</p>
            </div>

            <div>
              <h3 className="text-lg font-semibold mb-4">Select Cryptocurrency</h3>
              <div className="grid grid-cols-2 gap-4">
                {cryptoOptions.map((crypto) => (
                  <motion.button
                    key={crypto.id}
                    whileHover={{ scale: 1.05 }}
                    whileTap={{ scale: 0.95 }}
                    onClick={() => setSelectedCrypto(crypto.id)}
                    className="flex items-center gap-4 p-4 border-2 border-gray-200 rounded-xl hover:border-orange-500 hover:bg-orange-50 transition-all"
                  >
                    <div
                      className="w-12 h-12 rounded-full flex items-center justify-center text-white font-bold"
                      style={{ backgroundColor: crypto.color }}
                    >
                      {crypto.symbol.slice(0, 1)}
                    </div>
                    <div className="text-left">
                      <p className="font-semibold">{crypto.name}</p>
                      <p className="text-sm text-gray-600">{crypto.symbol}</p>
                    </div>
                  </motion.button>
                ))}
              </div>
            </div>
          </>
        ) : (
          <div className="space-y-6">
            <div className="text-center">
              <h3 className="text-xl font-bold mb-2">
                {cryptoOptions.find((c) => c.id === selectedCrypto)?.name}
              </h3>
              <p className="text-gray-600">Scan QR code or copy address below</p>
            </div>

            <div className="flex justify-center">
              <div className="bg-white p-4 rounded-xl border-4 border-gray-200">
                <QRCodeSVG
                  value={walletAddresses[selectedCrypto]}
                  size={200}
                  level="H"
                  includeMargin={true}
                />
              </div>
            </div>

            <div className="bg-gray-50 p-4 rounded-xl">
              <label className="text-sm font-medium text-gray-700 mb-2 block">
                Wallet Address
              </label>
              <div className="flex items-center gap-2">
                <input
                  type="text"
                  value={walletAddresses[selectedCrypto]}
                  readOnly
                  className="flex-1 px-4 py-2 bg-white border border-gray-300 rounded-lg text-sm font-mono"
                />
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => handleCopyAddress(walletAddresses[selectedCrypto])}
                >
                  {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                </Button>
              </div>
            </div>

            <div className="bg-yellow-50 p-4 rounded-lg">
              <p className="text-sm text-yellow-900">
                <strong>Note:</strong> Send exactly the amount shown. Your payment will be
                confirmed after network verification (typically 10-30 minutes).
              </p>
            </div>

            <div className="flex gap-3">
              <Button
                variant="outline"
                onClick={() => setSelectedCrypto(null)}
                className="flex-1"
              >
                Back
              </Button>
              <Button variant="primary" onClick={onClose} className="flex-1">
                I've Sent Payment
              </Button>
            </div>
          </div>
        )}
      </div>
    </Modal>
  )
}
